### ISSUE TITLE
Components of the driver board

### ISSUE THREAD

**Issue by Zeioth** [manna-harbour/crkbd#2]
I see you use [2 different resistors](https://photos.google.com/share/AF1QipN-g61hYbBhwOErVaDARWP4fk5UqttkEkYN1Qzg_oO31v05qlJ-Y73XoyO_E6Bccw/photo/AF1QipN-4XdJw_I9nCbBMfHg9UKqjpqQvdhvGvvAGQnb?key=RU5qcXplN3dXV1BnME42QnlFS0RwRlVaODQ1Z3hB) in the driver board. Could you list them please?

EDIT: Also, please indicate the AWG of the cables, thank you.

**Comment by manna-harbour** [comment]
> I see you use [2 different resistors](https://photos.google.com/share/AF1QipN-g61hYbBhwOErVaDARWP4fk5UqttkEkYN1Qzg_oO31v05qlJ-Y73XoyO_E6Bccw/photo/AF1QipN-4XdJw_I9nCbBMfHg9UKqjpqQvdhvGvvAGQnb?key=RU5qcXplN3dXV1BnME42QnlFS0RwRlVaODQ1Z3hB) in the driver board. Could you list them please?
> 
> EDIT: Also, please indicate the AWG of the cables, thank you.

The components are as follows:

- 1x 100kΩ resistor
- 2x 4.7kΩ resistor
- 1x 2.2µF capacitor

The components and circuit is represented in [this table](https://github.com/manna-harbour/crkbd/blob/master/trackpoint/readme.org#driver-board).  It's the same circuit as described in [this link](https://github.com/alonswartz/trackpoint) from [the documentation section](https://github.com/manna-harbour/crkbd/blob/master/trackpoint/readme.org#documentation), only re-arranged to match the oled port.

The pads on the controller board are quite closely spaced, so you need something fairly fine.  I used 28 AWG ribbon cable.

**Comment by Zeioth** [comment]
Can I ask what screws did you use to attach the R61 module to the crystal?
